### ISSUE TITLE
Format vidhosp pour 2019 ?

### ISSUE THREAD

**Issue by GuillaumePressiat** [jomuller/vidhospr#2]
Bonjour Dr Muller,

À mon tour de te remercier pour ce package !

Je peux éventuellement m'en charger si ce n'était pas fait de ton côté : disposes-tu d'une version "prête pour 2019" ?

Merci
Guillaume

**Comment by jomuller** [comment]
Merci pour ton message! Non, pour l'instant pas de version 2019 car la commande pour laquelle ce package a été créé arrive en général fin d'année dans mon établissement. Je n'ai malheureusement pas le temps de maintenir les choses au fil de l'eau, je ne le fais que lorsque cela m'est utile.
Mais l'adaptation pour 2019 ne devrait pas être problématique, surtout pour quelqu'un d'expérimenté comme toi !

**Comment by GuillaumePressiat** [comment]
Merci de ton retour,

Je viens de faire le csv pour 2019, en utilisant Tabula via le lien https://www.atih.sante.fr/formats-pmsi-2019. Au fait sur ce lien on trouve le fichier en xlsx pas uniquement le pdf.

https://github.com/GuillaumePressiat/lisvidhosp

Concernant la mise en forme des noms de variables avec ta fonction, c'est bien vu. Cela évite des tâches manuelles, et tant que les noms sont identiques d'une année sur l'autre, l'essentiel est là. Simple et efficace, du code facile à reprendre.

Mais, évidemment, j'ai sur mon mac eu quelques soucis liés aux encodages des caractères accentués et les "N°" donc j'ai du modifier la partie normalise. Un truc classique, mais pénible car du coup le code n'est pas forcément le même partout. 
Pour les accents, iconv donne "S'ejour" par exemple pour "Séjour". Dans ce cas de figure, j'utilise plutôt la fonction Unaccent que l'on trouve ici : https://data.hypotheses.org/564, je m'en suis juste inspiré ici.

Je précise parce que je ne garantis pas que j'ai exactement les mêmes noms de variables que toi du coup..
 
J'ai ajouté "..." dans la fonction d'import, ce qui permet de laisser plus de choix pour les imports.

Pour les étiquettes, un exemple avec `sjlabelled`, et les colonnes en caractère par défaut, sur les 1000 premières lignes. Ça peut rester en dehors du package. 

```r
u <- importe_vidhosp('~/Documents/magic/vid-hosp_2019', 
                     col_types = readr::cols(.default = readr::col_character()),
                     n_max = 1e3)
etiquettes <- lisvidhosp::formats %>% 
          filter(format_version == "V013", !is.na(debut)) %>% 
          pull(nom)

u <- u %>% sjlabelled::set_label(etiquettes)
```

Je n'ai pas pris le temps de re-générer la doc avec roxygen. J'y ai juste ajouté le lien vers le site de l'ATIH pour les formats 2019.


À plus, et merci
Guillaume

**Comment by jomuller** [comment]
Super! Merci. Pourrais-tu dans la description t'ajouter dans les auteurs et mettre la date à jour ? Je ferai un PULL sur nos dépots après. Encore merci, en particulier pour l'astuce sur les accents  !

**Comment by GuillaumePressiat** [comment]
C'est fait.

Dispo si besoin,

**Comment by jomuller** [comment]
Merci !
